 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: reactivestock-broker
   namespace: default
   labels:
     app: reactivestock-broker
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: reactivestock-broker
   template:
     metadata:
       labels:
         app: reactivestock-broker
         actorSystemName: reactivestock-broker
     spec:
       serviceAccountName: reactivestock-broker-sa
       containers:
       - name: reactivestock-broker
         image: reactivestock-broker:0.1-SNAPSHOT
         ports:
         - name: http
           containerPort: 9010
         - name: remoting
           containerPort: 2552
           protocol: TCP
         - name: management
           containerPort: 8559
           protocol: TCP           
         envFrom:
         - configMapRef:
             name: reactivestock-broker-config
         env:
           - name: "HTTP_BIND_ADDRESS"
             value: "0.0.0.0"
           - name: JAVA_OPTS
             value: "-Dconfig.resource=application.prod.conf -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
           - name: "HOST_ADDRESS"
             valueFrom:
               fieldRef:
                 fieldPath: "status.podIP"  
           - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
             valueFrom:
               fieldRef:
                 apiVersion: v1
                 fieldPath: "metadata.labels['app']"    
         resources:
           requests:
             memory: "256Mi"
             cpu: "100m"
           limits:
             memory: "1Gi"
         livenessProbe:
           httpGet:
             path: /alive
             port: management
         readinessProbe:
           httpGet:
             path: /ready
             port: management
