 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: reactivestock-wiretransfer
   name: reactivestock-wiretransfer-svc
 spec:
   type: ClusterIP
   selector:
     app: reactivestock-wiretransfer
   ports:
   - name: reactivestock-wiretransfer-http
     port: 9020
     targetPort: http
