apiVersion: v1
kind: ConfigMap
metadata:
  name: reactivestock-wiretransfer-config
data:
  CASSANDRA_CONTACT_POINT: "cassandra.cassandra"
  KAFKA_BROKERS_SERVICE_URL: "reactivestock-strimzi-kafka-bootstrap.kafka:9092"
  ALLOWED_HOST: "reactivestock-wiretransfer-svc.default"
  PORTFOLIO_SERVICE_URL: "http://reactivestock-portfolio-svc.default:9000"