 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: orders
   name: reactivestock-portfolio-svc
 spec:
   type: ClusterIP
   selector:
     app: reactivestock-portfolio
   ports:
   - name: reactivestock-portfolio-http
     port: 9000
     targetPort: http
