   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: reactivestock-bff
     labels:
       app: reactivestock-bff
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: reactivestock-bff
     template:
       metadata:
         labels:
           app: reactivestock-bff
         annotations: # Annoations used for Enterprise Suite Metrics
           "prometheus.io/scrape": "true"
           "prometheus.io/scheme": "http"
           "prometheus.io/path": "/metrics"
           "prometheus.io/port": "9001"
       spec:
         containers:
         - name: reactivestock-bff
           image: bff:1.0-SNAPSHOT
           ports:
           - name: bff-http
             containerPort: 9200
           - name: prometheus # Used for Enterprise Suite Metrics
             containerPort: 9001
             protocol: TCP
           envFrom:
             - configMapRef:
                 name: bff-config
           env:
             - name: "HTTP_BIND_ADDRESS"
               value: "0.0.0.0"
             - name: JAVA_OPTS
               value: "-Dconfig.file=/etc/reactivestock/production.conf -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
           resources:
             requests:
               memory: "256Mi"
               cpu: "100m"
             limits:
               memory: "2Gi"
           readinessProbe:
             httpGet:
               path: /healthz
               port: 9200
               httpHeaders:
               - name: Host
                 value: reactivestock.com
             initialDelaySeconds: 5
             periodSeconds: 3
           livenessProbe:
             httpGet:
               path: /healthz
               port: 9200
               httpHeaders:
               - name: Host
                 value: reactivestock.com
             initialDelaySeconds: 60
             periodSeconds: 30
           volumeMounts:
             - name: app-creds
               mountPath: "/etc/reactivestock/"
               readOnly: true
         volumes:
           - name: app-creds
             secret:
               secretName: reactivestock-secrets




