   apiVersion: v1
   kind: Service
   metadata:
     labels:
       app: reactivestock-bff
     name: reactivestock-bff-svc
   spec:
     type: ClusterIP
     selector:
       app: reactivestock-bff
     ports:
     - name: http-play
       port: 80
       targetPort: bff-http
